### ISSUE TITLE
Játékmenet koncepció kialakítása

### ISSUE THREAD

**Issue by halijy** [Tschokee/Serious_game#10]
- Elindul a játék, mi történik? Egyből game start vagy valami press enter to start?
- Ezután van a játék. Mi a háttér? Egy szín? Egy kép? Animáció?
- Meg tudunk fogalmazni egy játékmenetet? Mit lehet csinálni? Mi van a képernyőn? 
- Mikor van vége egy játéknak? Végtelen ismétlődik? Idő? Megoldás darab alapján?
- Mi történik ha vége a játéknak? Főmenü? Score screen?

Ezeket úgy kellene megválaszolni, hogy most egy kereten dolgozok, amit minden játékra rá lehet húzni. Csak képeket meg a generálás módját cseréljük.

**Comment by Tschokee** [comment]
Elindul a játék, mi történik? Egyből game start vagy valami press enter to start?
jó ahogy most van

Ezután van a játék. Mi a háttér? Egy szín? Egy kép? Animáció?
szintén maradhat

Meg tudunk fogalmazni egy játékmenetet? Mit lehet csinálni? Mi van a képernyőn?
úgy kellene kinézni mint a tényleges játékon (pdf, word)
persze nem pontosan, csak az alap koncepció legyen meg
vannak random szétszórva a mozgatható dolgok 
van középen egy tároló rész, ahova mozgatni kell ezeket

Mikor van vége egy játéknak?  
ha az összes mozgatható dolog a helyére került ( helye: ahova a felhasználó rakja )

Végtelen ismétlődik?
nem, egyszer lehet bemozgatni az elemeket, aztán valami értékelés jön

Idő?
egyenlőre nincs rá korlát

Megoldás darab alapján?
mindegyikhez tartozik értékelőlap, de igen darab alpján

Mi történik ha vége a játéknak? Főmenü? Score screen?
eredményjelző valami

**Comment by Tschokee** [comment]
Ez hogy áll?

**Comment by halijy** [comment]
- Meg tudunk fogalmazni egy játékmenetet? Mit lehet csinálni? Mi van a képernyőn?

Ezt pontosítani kellene.

**Comment by Tschokee** [comment]
Na ilyesmire gondoltam:
- indul a játék, jó lenne ezzel a háttérszínnel, bohóccal és felhővel:
  ![start](https://cloud.githubusercontent.com/assets/2843067/7162099/f61a38fa-e392-11e4-95fa-0118aa0db63e.jpg)
- a lufit bemozgatom oda, ahova gondolom a megoldást:
  ![move](https://cloud.githubusercontent.com/assets/2843067/7162111/1011117a-e393-11e4-961f-6f4a45dcb7a8.jpg)
- aztán az ellenőrzés gombra kattintva megjelenik az eredmény és kiírja, hogy 10-ből mennyi lett meg
  ![check](https://cloud.githubusercontent.com/assets/2843067/7162125/21c69c0a-e393-11e4-9c62-797e5c695459.jpg)

**Comment by halijy** [comment]
Ha vonalakat kellene húzgálni még működhetne is, de így szerintem ( ha szeretnénk egy minimális minőséget) nem jó. Most ráhúzod a lufit a (10:1)-es sárga lufira, hogy húzod rá a (9:1)-es kékre, majd a (8:1) es pirosra?
Amit ezzel akarok mondani, hogy az az 5 színes lufis kép számunkra használhatatlan. Valamivel azt helyettesíteni kell.

**Comment by Tschokee** [comment]
A) kék lufik (eredmények) átlátszóak kb 60%-ban
B) szétszedjük a kérdés lufikat
melyik az egyszerűbb?

**Comment by halijy** [comment]
Gameplay szempontjából kellene megközelíteni, tehát gondolom a szétszedve jobb, úgy lesz egyértelmű, hogy mire akarod ráhelyezni a lufit.

**Comment by Tschokee** [comment]
jó írok ki rá feladatot

**Comment by Tschokee** [comment]
azt hiszem ezt lezárhatom
