### ISSUE TITLE
Ütközéskezelés

### ISSUE THREAD

**Issue by Tschokee** [Tschokee/Serious_game#11]
pl egy lufit (5) ráhúz a felhasználó a kérdésre (10:2)

**Comment by halijy** [comment]
Csak a Collusion metódust kellene implementálni ehhez.
2 GameContent osztály hasonlít össze, true ha ütköznek.
ami kellhet:
- ViewboxHeight
- ViewboxWidth
- PosX
- PosY

**Comment by Alterion** [comment]
A Collusion-ben csak azt nézzem h ütköznek e és a helyességellenörzést egy másik metódusban amit itt meg is hívok, vagy mehet egyből ebbe?

**Comment by Alterion** [comment]
Megcsináltam az ütközéskezelést, a két object érétkének a vizsgálata még megbeszélést kíván, a létrehozásuk szempontjából.

**Comment by halijy** [comment]
Az a metódus így jó, ahogy most megcsináltam.  Az objecteknek van egy PairID mezője amit erre szántam hogy amikor létrehozod, ha az egyezik 2 elemnél, akkor azzal kell párosítani.

**Comment by Alterion** [comment]
Ok

**Comment by halijy** [comment]
Szerintem ez így teljesen jó és zárható.
