### ISSUE TITLE
Értékelő felület kialakítása

### ISSUE THREAD

**Issue by Tschokee** [Tschokee/Serious_game#13]
elején elég csak számokkal pl 6/10

**Comment by halijy** [comment]
mivel a játékmenetben jelenlegi felállás alapján nem lehet hibázni, hiszen akkor van vége ha mindent megoldottál, így jelenlegi mindig csak azt írná hogy 100% .
tehát ezt pontosítani kell.

**Comment by Tschokee** [comment]
másik issue-ban írtam hogy kellene kinézni

**Comment by Tschokee** [comment]
egyenlőre zárom, mert jónak tűnik
