### ISSUE TITLE
Osztóka játék

### ISSUE THREAD

**Issue by Tschokee** [Tschokee/Serious_game#16]

**Comment by halijy** [comment]
Refaktoroztam, hogy tudjatok normálisan haladni. Csak ezt az egy fájlt kell módosítgatni.
https://github.com/Tschokee/Serious_game/blob/master/SeriousGameWPF/SeriousGameWPF/SeriousGameWPF/Games/Osztoka.cs

**Comment by Tschokee** [comment]
lezárom ezt a feladatot, mert így nem sok értelme van :)
