### ISSUE TITLE
Lufikban a számok töltsék ki minél jobban a helyet

### ISSUE THREAD

**Issue by Tschokee** [Tschokee/Serious_game#25]

**Comment by halijy** [comment]
Első verzióként egy FontSize propertyt csináltam a GameContent-hez és ezt fordítási időben a MainMenuHandler.FontSize módosításával változtatható.
Mivel ViewPort-al van csinálva ezért a FontSize nem a tényleges kirajzolt Font méretét adja meg, hanem hogy a kirajzolt lufihoz képest mekkora legyen.

**Comment by Tschokee** [comment]
oké
