### ISSUE TITLE
Új alert!

### ISSUE THREAD

**Issue by Tschokee** [Tschokee/Serious_game#27]
@ MainWindow.xaml.cs 25.soráról van szó
ha a PirateVersion() függvény visszatérési értéke FALSE: akkor jelenjen meg egy kis ablak valami szöveggel (a kódban van, megtalálod)
legyen egy OK, gomb benne
OK után lépjen ki a játék

**Comment by halijy** [comment]
nézd meg hogy így gondoltad e

**Comment by Tschokee** [comment]
oké, délután meglesem

**Comment by Tschokee** [comment]
faja
