### ISSUE TITLE
Back to selection

### ISSUE THREAD

**Issue by Tschokee** [Tschokee/Serious_game#29]
Legyen egy olyan gomb a menüsoron, vagy a játékban (ahol egyszerűbb), hogy visszadob a feladat "nehézség" állítóra, tehát oda ahol kiválasztod 1-10ig a számokat
Jó lenne, hogy ha ez csak akkor látszódna, mikor ténylegesen játszunk

**Comment by halijy** [comment]
Elkezdtem, de egy érthetelten bugom van, majd kijavítom jövőhéten mert nekem ez a hét ennyi volt.

**Comment by Tschokee** [comment]
Jójó

**Comment by halijy** [comment]
Remélem nem bugos, tehát kész:D
