### ISSUE TITLE
Képek kigyűjtése és szabványméretezése

### ISSUE THREAD

**Issue by Tschokee** [Tschokee/Serious_game#3]
ahogy elfogadhatónak látod
formátum: png

**Comment by Alterion** [comment]
Megcsináltam a pdf-ekben lévő képeket, még kell 4 jatékhoz kép majd valahonnan

**Comment by halijy** [comment]
Az osztóka képéből kiindulva, a szorzóka képe szerintem nem jó.

**Comment by Alterion** [comment]
Akkor keresünk másikat. A méretek jók?

**Comment by halijy** [comment]
Az a nem jó az szorzókában, mintha szét lenne húzva.

![szorzoka](https://cloud.githubusercontent.com/assets/2454555/7045037/fdea5b08-ddf9-11e4-9786-f3948f63c002.png) vs
![osztoka](https://cloud.githubusercontent.com/assets/2454555/7045041/086f87ec-ddfa-11e4-8d55-89b02161e82c.jpg)

**Comment by Alterion** [comment]
Nézd meg amit feltöltöttem, úgy jó?

**Comment by halijy** [comment]
Zsoltinak kellene inkább megmondania, hogy ő honnan szerezte ezt a képet:
Serious_game/SeriousGameWPF/SeriousGameWPF/SeriousGameWPF/Images/osztoka.jpg

Mert ennek jó a minősége, így kellene szerintem a tőbbi is. 
Amúgy én a minőségen szarozok most nem a képarányon.

**Comment by Tschokee** [comment]
Én azt a képet is a pdf/doc fájlokból szedtem

**Comment by Tschokee** [comment]
Nézzük már meg képek nélkül, elfogadható designnal és csak szövegesen
