### ISSUE TITLE
Egységes ablakméret

### ISSUE THREAD

**Issue by Tschokee** [Tschokee/Serious_game#30]
A jelenlegi működés annyira nem tetszik most:
Start -> Ablakméret: X -> játék indítás -> Ablakméret: ~1.2X -> játék vége -> Ablakméret marad ~1.2X

1) megoldás: ablakméret visszaáll X-re játék vége után
2) megoldás: ablakméret ~1.2X indulásnál is

Amelyiket egyszerűbb megvalósítani, azt kellene (sztem 2) )

**Comment by halijy** [comment]
Na ha nem vagyok, hülye akkor megoldva. 2- es megoldással.
