### ISSUE TITLE
Ellenőrzés bug

### ISSUE THREAD

**Issue by Tschokee** [Tschokee/Serious_game#38]
Eset:
Főmenü->osztóka->tetszőleges játék-> 1 lufit ráhúzok a kérdésre -> ellenőrzés (eddig jó)
-> back / mode selection -> tetszőleges játék -> 1 lufit ráhúzok a kérdésre -> ellenőrzés -----itt újraindul és a mode selection is tönkremegy

**Comment by halijy** [comment]
Szerintem javítva.

**Comment by Tschokee** [comment]
yap
úgy tűnik
