### ISSUE TITLE
1-10 választó mechanika

### ISSUE THREAD

**Issue by Tschokee** [Tschokee/Serious_game#4]
legjobb lenne ha a főmenü ablakában történne valami animáció formájában
új oldalon is elfogadható

**Comment by halijy** [comment]
Várom a jelenlegi verzió véleményezését. + van benne egy bug amit nem bírok kijavítani(ha valaki ráakarna nézni):->
![image](https://cloud.githubusercontent.com/assets/2454555/7067303/725a0bf2-deca-11e4-92b7-6e4b072f4580.png)
Be kellene jönnie a scrollbarnak, de nem jön mert szarul méretezi be a Canvas-t, de ugyanez a főmenüben működik.
MainMenuHandler.CalculatePositionFor(...)

**Comment by Tschokee** [comment]
Tetszik az animáció és a design,
a választó gombok szerintem majd lehetnek kisebbek, de egyenlőre jó.
Legyen meg 1-10ig a számozás. 
Írok ki újabb feladatokat is

**Comment by halijy** [comment]
DataContext probléma volt végül.
Most azt kell kitalálni, hogy ha rámész egy módra, az hogy indítsa el a megfelelő játékot.
