### ISSUE TITLE
Nem jelenik meg a scrollbar a választó ablakban

### ISSUE THREAD

**Issue by Tschokee** [Tschokee/Serious_game#5]

**Comment by halijy** [comment]
Én úgy gondolom, hogy a probléma megoldva. Nem tudom, hogy kinek kellene lezárni az issuet? én most lezárom, de szóljatok ha nem ez a dolgok menete.

**Comment by Tschokee** [comment]
Úgy csináljuk, hogy mindig az zárja le aki kiírta
Ti is vehettek fel újakat, ha gondoljátok
