### ISSUE TITLE
A kiválasztott számhoz tartozó játék töltődik be

### ISSUE THREAD

**Issue by Tschokee** [Tschokee/Serious_game#8]

**Comment by halijy** [comment]
Hogy működik most:
GameMode paramétert vágja át a Game osztálynak, a Game osztály GenerateActiveContent metódusa pedig a paraméter alapján létrehozza a felületet.
Tehát minden GameMode-hoz definiálni kell egy generálási módot.
Maga a mechanika szerintem jó és zárható ha megfelelő így a működés.

**Comment by Tschokee** [comment]
jó lesz
