### ISSUE TITLE
Főmenüben csak szöveges gombok legyenek

### ISSUE THREAD

**Issue by Tschokee** [Tschokee/Serious_game#9]
Elég csudák azok a képek szerintem, nézzük már meg nélkülük

**Comment by halijy** [comment]
Na miközben ezt próbáltam csinálni, totál szétcsesztem mindent, azért van ott 2 értelmetlen revert (így volt a legegyszerűbb helyreállítani). 
Nem találtam megoldást arra, hogy hogyan lehetne eventet kezelni styleban szóval maradt a hardcoded datatemplate. Ha tudjátok hogy kell várom a megoldást.

**Comment by halijy** [comment]
![image](https://cloud.githubusercontent.com/assets/2454555/7084487/18a93926-df6e-11e4-990e-2b7be557cdaa.png)

**Comment by Tschokee** [comment]
jó lesz egyenlőre
